version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: station_ops_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: station
      POSTGRES_PASSWORD: stationpw
      POSTGRES_DB: station_ops
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
